// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUvrlCDtdIWPRbKHnct9_bxYq7X3qEcGQ',
    appId: '1:722238446570:web:a6fdb6229b8d7ca01ff093',
    messagingSenderId: '722238446570',
    projectId: 'swarna-agilis-feature',
    authDomain: 'swarna-agilis-feature.firebaseapp.com',
    storageBucket: 'swarna-agilis-feature.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaRN4dzfVz7J9SjZS0_oWVlV5JJVEIuE4',
    appId: '1:722238446570:android:1d82c0b24b4d87421ff093',
    messagingSenderId: '722238446570',
    projectId: 'swarna-agilis-feature',
    storageBucket: 'swarna-agilis-feature.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PEBWrcZ2-03ZY2FMqK25Q0J2M2P-uLM',
    appId: '1:722238446570:ios:a95ff735508f6a9f1ff093',
    messagingSenderId: '722238446570',
    projectId: 'swarna-agilis-feature',
    storageBucket: 'swarna-agilis-feature.appspot.com',
    iosClientId: '722238446570-rs6h922oknnkmki83nnjpd6b3jli96vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PEBWrcZ2-03ZY2FMqK25Q0J2M2P-uLM',
    appId: '1:722238446570:ios:a95ff735508f6a9f1ff093',
    messagingSenderId: '722238446570',
    projectId: 'swarna-agilis-feature',
    storageBucket: 'swarna-agilis-feature.appspot.com',
    iosClientId: '722238446570-rs6h922oknnkmki83nnjpd6b3jli96vj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFlow',
  );
}
